# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dna.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dna.proto',
  package='RemyBuffers',
  serialized_pb='\n\tdna.proto\x12\x0bRemyBuffers\"\x87\x01\n\x0bWhiskerTree\x12(\n\x06\x64omain\x18\x01 \x01(\x0b\x32\x18.RemyBuffers.MemoryRange\x12*\n\x08\x63hildren\x18\x02 \x03(\x0b\x32\x18.RemyBuffers.WhiskerTree\x12\"\n\x04leaf\x18\x03 \x01(\x0b\x32\x14.RemyBuffers.Whisker\"U\n\x0bMemoryRange\x12\"\n\x05lower\x18\x0b \x01(\x0b\x32\x13.RemyBuffers.Memory\x12\"\n\x05upper\x18\x0c \x01(\x0b\x32\x13.RemyBuffers.Memory\"H\n\x06Memory\x12\x15\n\rrec_send_ewma\x18\x15 \x01(\x01\x12\x14\n\x0crec_rec_ewma\x18\x16 \x01(\x01\x12\x11\n\trtt_ratio\x18\x17 \x01(\x01\"y\n\x07Whisker\x12\x18\n\x10window_increment\x18\x1f \x01(\x11\x12\x17\n\x0fwindow_multiple\x18  \x01(\x01\x12\x11\n\tintersend\x18! \x01(\x01\x12(\n\x06\x64omain\x18\" \x01(\x0b\x32\x18.RemyBuffers.MemoryRange')




_WHISKERTREE = _descriptor.Descriptor(
  name='WhiskerTree',
  full_name='RemyBuffers.WhiskerTree',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='domain', full_name='RemyBuffers.WhiskerTree.domain', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='children', full_name='RemyBuffers.WhiskerTree.children', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='leaf', full_name='RemyBuffers.WhiskerTree.leaf', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=162,
)


_MEMORYRANGE = _descriptor.Descriptor(
  name='MemoryRange',
  full_name='RemyBuffers.MemoryRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lower', full_name='RemyBuffers.MemoryRange.lower', index=0,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='upper', full_name='RemyBuffers.MemoryRange.upper', index=1,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=164,
  serialized_end=249,
)


_MEMORY = _descriptor.Descriptor(
  name='Memory',
  full_name='RemyBuffers.Memory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rec_send_ewma', full_name='RemyBuffers.Memory.rec_send_ewma', index=0,
      number=21, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rec_rec_ewma', full_name='RemyBuffers.Memory.rec_rec_ewma', index=1,
      number=22, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rtt_ratio', full_name='RemyBuffers.Memory.rtt_ratio', index=2,
      number=23, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=251,
  serialized_end=323,
)


_WHISKER = _descriptor.Descriptor(
  name='Whisker',
  full_name='RemyBuffers.Whisker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='window_increment', full_name='RemyBuffers.Whisker.window_increment', index=0,
      number=31, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='window_multiple', full_name='RemyBuffers.Whisker.window_multiple', index=1,
      number=32, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intersend', full_name='RemyBuffers.Whisker.intersend', index=2,
      number=33, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='domain', full_name='RemyBuffers.Whisker.domain', index=3,
      number=34, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=325,
  serialized_end=446,
)

_WHISKERTREE.fields_by_name['domain'].message_type = _MEMORYRANGE
_WHISKERTREE.fields_by_name['children'].message_type = _WHISKERTREE
_WHISKERTREE.fields_by_name['leaf'].message_type = _WHISKER
_MEMORYRANGE.fields_by_name['lower'].message_type = _MEMORY
_MEMORYRANGE.fields_by_name['upper'].message_type = _MEMORY
_WHISKER.fields_by_name['domain'].message_type = _MEMORYRANGE
DESCRIPTOR.message_types_by_name['WhiskerTree'] = _WHISKERTREE
DESCRIPTOR.message_types_by_name['MemoryRange'] = _MEMORYRANGE
DESCRIPTOR.message_types_by_name['Memory'] = _MEMORY
DESCRIPTOR.message_types_by_name['Whisker'] = _WHISKER

class WhiskerTree(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WHISKERTREE

  # @@protoc_insertion_point(class_scope:RemyBuffers.WhiskerTree)

class MemoryRange(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MEMORYRANGE

  # @@protoc_insertion_point(class_scope:RemyBuffers.MemoryRange)

class Memory(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MEMORY

  # @@protoc_insertion_point(class_scope:RemyBuffers.Memory)

class Whisker(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WHISKER

  # @@protoc_insertion_point(class_scope:RemyBuffers.Whisker)


# @@protoc_insertion_point(module_scope)
